### ISSUE TITLE
Revert to recent location?

### ISSUE THREAD

**Issue by lostmonster** [Arkkimaagi/Bookmark#1]
While I work, my workspace moves around quite a bit. Let's say I have a reference bookmark 1 with this plugin.  It might be a good idea to also include a shortcut to allow users to revert back to their recent location without having to create a bookmark for it. 

Say I have multiple work spaces, A, B, C, etc. I would like to be able to jump betwen A > 1 > A easily without having to bookmark A, since I will often be working between workspace A, B, and C. 

Hope this makes sense!

**Comment by Arkkimaagi** [comment]
I did not quite understand what's suggested here. Do you mean that the bookmark plugin would save the current location before moving to the bookmarked location and you could return there somehow. Hmm, interesting idea, will think about how to implement it.

**Comment by lostmonster** [comment]
It's difficult to explain, so I apologize if I was unclear.  Your plugin is very powerful, but can be even more so if I can revert to my last viewed location. That way, I can jump to my bookmark, then jump back with ease. 

I understand that this might cause significant lag, since the plugin would always have to be "on" by remembering where the user "was" before jumping to a bookmark, but it's simply an idea!

**Comment by Arkkimaagi** [comment]
I hope the version 1.1.0 solves your need. :)

If it does, we can close this issue, right?

**Comment by Arkkimaagi** [comment]
@lostmonster Did you check this new feature? Can we close the issue? :)

**Comment by lostmonster** [comment]
Yes! So sorry for the delay, but this seems to enhance the functionality of this plugin GREATLY.  Thank you so much! You can close this issue.
