### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [Arkkimaagi/Bookmark#4]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by Arkkimaagi** [comment]
I think I have solved this issue in version 1.1.1, but how can I be sure?

**Comment by bomberstudios** [comment]
Download the beta from https://sketchapp.com/beta/ and see if it works there : )

**Comment by Arkkimaagi** [comment]
Do I need to make an update to test it out?

**Comment by bomberstudios** [comment]
You can probably test it by modifying a local v1.0 plugin, adding the appcast attribute and have it update to the 1.1.1 you just created.

**Comment by Arkkimaagi** [comment]
Okay, thank you, seems to be working :)
